;;; vscode-light-theme.el --- VS Code "Light+" palette -*- lexical-binding: t -*-

;;; Commentary:
;; VS Code 標準ライトテーマ (Default Light+) の配色を Emacs の face に写したもの。

;;; Code:

(deftheme vscode-light "VS Code Default Light+ colors.")

(let ((bg      "#FFFFFF") (fg      "#000000")
      (kw      "#0000FF") (ctrl    "#AF00DB") (str     "#A31515")
      (cmt     "#008000") (num     "#098658") (fn      "#795E26")
      (type    "#267F99") (var     "#001080") (const   "#0070C1")
      (regex   "#811F3F") (esc     "#EE0000")
      (sel     "#ADD6FF") (hl      "#F3F3F3") (panel   "#F3F3F3")
      (border  "#E5E5E5") (lnum    "#237893") (lnum-cur "#0B216F")
      (status  "#007ACC") (find    "#A8AC94") (find2   "#F8C9AB")
      (link    "#006AB1") (link-v  "#68217A")
      (err     "#E51400") (warn    "#BF8803") (info    "#1A85FF")
      (shadow  "#A0A0A0") (list-sel "#0060C0")
      (add-bg  "#E6FFEC") (del-bg  "#FFEBE9") (add-hi  "#ACF2BD") (del-hi  "#FFC0C0")
      (md-head "#800000") (md-bold "#000080"))
  (custom-theme-set-faces
   'vscode-light
   ;; 基本
   `(default        ((t (:background ,bg :foreground ,fg))))
   `(cursor         ((t (:background ,fg))))
   `(region         ((t (:background ,sel :extend t))))
   `(secondary-selection ((t (:background "#D6EAFF" :extend t))))
   `(highlight      ((t (:background "#E8E8E8"))))
   `(hl-line        ((t (:background ,hl :extend t))))
   `(shadow         ((t (:foreground ,shadow))))
   `(link           ((t (:foreground ,link :underline t))))
   `(link-visited   ((t (:foreground ,link-v :underline t))))
   `(error          ((t (:foreground ,err :weight bold))))
   `(warning        ((t (:foreground ,warn :weight bold))))
   `(success        ((t (:foreground ,cmt :weight bold))))
   `(match          ((t (:background ,find2))))
   `(isearch        ((t (:background ,find :foreground ,fg))))
   `(lazy-highlight ((t (:background ,find2))))
   `(isearch-fail   ((t (:background ,del-hi))))
   `(show-paren-match    ((t (:background "#DCE9DC" :weight bold))))
   `(show-paren-mismatch ((t (:background ,err :foreground ,bg))))
   `(trailing-whitespace ((t (:background "#FADADD"))))
   `(minibuffer-prompt   ((t (:foreground ,link :weight bold))))
   `(vertical-border     ((t (:foreground "#C8C8C8"))))
   `(escape-glyph        ((t (:foreground ,esc))))
   `(nobreak-space       ((t (:background "#E0E0E0"))))

   ;; 行番号 / モードライン
   `(line-number              ((t (:foreground ,lnum :background ,bg))))
   `(line-number-current-line ((t (:foreground ,lnum-cur :background ,bg :weight bold))))
   `(mode-line          ((t (:background ,status :foreground ,bg :box nil))))
   `(mode-line-inactive ((t (:background ,panel :foreground "#616161" :box nil))))
   `(mode-line-buffer-id ((t (:weight bold))))
   `(header-line        ((t (:background ,panel :foreground ,fg))))
   `(fringe             ((t (:background ,bg))))
   `(window-divider     ((t (:foreground ,border))))

   ;; font-lock
   `(font-lock-keyword-face       ((t (:foreground ,kw))))
   `(font-lock-builtin-face       ((t (:foreground ,kw))))
   `(font-lock-preprocessor-face  ((t (:foreground ,ctrl))))
   `(font-lock-string-face        ((t (:foreground ,str))))
   `(font-lock-doc-face           ((t (:foreground ,cmt))))
   `(font-lock-comment-face       ((t (:foreground ,cmt))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,cmt))))
   `(font-lock-constant-face      ((t (:foreground ,const))))
   `(font-lock-number-face        ((t (:foreground ,num))))
   `(font-lock-escape-face        ((t (:foreground ,esc))))
   `(font-lock-regexp-face        ((t (:foreground ,regex))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,regex :weight bold))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,regex :weight bold))))
   `(font-lock-function-name-face ((t (:foreground ,fn))))
   `(font-lock-function-call-face ((t (:foreground ,fn))))
   `(font-lock-type-face          ((t (:foreground ,type))))
   `(font-lock-variable-name-face ((t (:foreground ,var))))
   `(font-lock-variable-use-face  ((t (:foreground ,var))))
   `(font-lock-property-name-face ((t (:foreground ,var))))
   `(font-lock-property-use-face  ((t (:foreground ,var))))
   `(font-lock-operator-face      ((t (:foreground ,fg))))
   `(font-lock-punctuation-face   ((t (:foreground ,fg))))
   `(font-lock-bracket-face       ((t (:foreground ,fg))))
   `(font-lock-delimiter-face     ((t (:foreground ,fg))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,fg))))
   `(font-lock-negation-char-face ((t (:foreground ,fg))))
   `(font-lock-warning-face       ((t (:foreground ,err :weight bold))))

   ;; 補完 (fido / completion-preview / which-key)
   `(icomplete-selected-match ((t (:background ,list-sel :foreground ,bg :extend t))))
   `(icomplete-first-match    ((t (:weight bold))))
   `(completions-common-part  ((t (:foreground "#0066BF" :weight bold))))
   `(completions-first-difference ((t (:weight bold))))
   `(completion-preview        ((t (:foreground ,shadow))))
   `(completion-preview-common ((t (:foreground ,shadow :underline t))))
   `(completion-preview-exact  ((t (:foreground ,shadow :underline t))))
   `(which-key-key-face        ((t (:foreground ,const))))
   `(which-key-command-description-face ((t (:foreground ,fg))))

   ;; whitespace
   `(whitespace-tab      ((t (:background "#EEEEEE"))))
   `(whitespace-space    ((t (:background "#E0E0E0"))))
   `(whitespace-trailing ((t (:background "#FADADD"))))

   ;; flymake / eglot / eldoc
   `(flymake-error   ((t (:underline (:style wave :color ,err)))))
   `(flymake-warning ((t (:underline (:style wave :color ,warn)))))
   `(flymake-note    ((t (:underline (:style wave :color ,info)))))
   `(eglot-highlight-symbol-face ((t (:background "#DFDFDF"))))
   `(eldoc-highlight-function-argument ((t (:foreground ,fn :weight bold))))

   ;; avy
   `(avy-lead-face   ((t (:background ,err :foreground ,bg :weight bold))))
   `(avy-lead-face-0 ((t (:background ,link :foreground ,bg :weight bold))))
   `(avy-lead-face-1 ((t (:background ,shadow :foreground ,bg))))
   `(avy-lead-face-2 ((t (:background ,cmt :foreground ,bg :weight bold))))

   ;; diff / vc
   `(diff-added           ((t (:background ,add-bg :extend t))))
   `(diff-removed         ((t (:background ,del-bg :extend t))))
   `(diff-refine-added    ((t (:background ,add-hi))))
   `(diff-refine-removed  ((t (:background ,del-hi))))
   `(diff-header          ((t (:background ,panel :extend t))))
   `(diff-file-header     ((t (:background ,panel :weight bold :extend t))))
   `(diff-hunk-header     ((t (:foreground ,ctrl :background ,panel :extend t))))

   ;; markdown-ts-mode
   `(markdown-ts-heading-1  ((t (:foreground ,md-head :weight bold :height 1.0))))
   `(markdown-ts-heading-2  ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-heading-3  ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-heading-4  ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-heading-5  ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-heading-6  ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-setext-heading ((t (:foreground ,md-head :weight bold))))
   `(markdown-ts-bold       ((t (:foreground ,md-bold :weight bold))))
   `(markdown-ts-emphasis   ((t (:slant italic))))
   `(markdown-ts-strikethrough ((t (:strike-through t))))
   `(markdown-ts-code-span  ((t (:foreground ,md-head :background ,hl))))
   `(markdown-ts-code-block ((t (:background ,hl :extend t))))
   `(markdown-ts-in-code-block ((t (:background ,hl :extend t))))
   `(markdown-ts-indented-code-block ((t (:background ,hl :extend t))))
   `(markdown-ts-language-keyword ((t (:foreground ,kw))))
   `(markdown-ts-block-quote ((t (:foreground "#616161" :slant italic))))
   `(markdown-ts-list-marker ((t (:foreground ,kw :weight bold))))
   `(markdown-ts-link        ((t (:foreground ,link :underline t))))
   `(markdown-ts-link-destination ((t (:foreground ,link))))
   `(markdown-ts-delimiter   ((t (:foreground ,shadow))))
   `(markdown-ts-thematic-break ((t (:foreground ,shadow))))
   `(markdown-ts-html-tag    ((t (:foreground "#800000"))))
   `(markdown-ts-table-header ((t (:weight bold))))
   `(markdown-ts-task-checked   ((t (:foreground ,cmt))))
   `(markdown-ts-task-unchecked ((t (:foreground ,shadow))))))

(provide-theme 'vscode-light)
;;; vscode-light-theme.el ends here
